project_id = "cxmuzperkittvibslnff"

[functions.send-notification-emails]
verify_jwt = false

[functions.trigger-notification-emails]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.submit-anonymous-report]
verify_jwt = false

[functions.anonymous-report-messaging]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = true

[functions.accept-team-invitation]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.translate-text]
verify_jwt = true

[functions.encrypt-report-data]
verify_jwt = false

[functions.decrypt-report-data]
verify_jwt = true